name: xeus-python-kernel
channels:
  - https://conda.anaconda.org/michaelweinold/label/emscripten # for platform-specific version of bw2data https://anaconda.org/michaelweinold/repo/files?type=any&label=emscripten
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - ipycanvas
  - better_exceptions_fork
  - bw2io=0.9.dev34